name: Terraform - PROD Infrastructure

on:
  push:
    tags:
      - 'v*'
    paths:
      - 'service-a/infra/prod/**'
  workflow_dispatch:

env:
  AWS_REGION: us-east-1

jobs:
  terraform-prod:
    name: Terraform Plan (PROD)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: service-a/infra/prod

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Check Format
        run: terraform fmt -check

      - name: Init
        run: terraform init

      - name: Validate
        run: terraform validate

      - name: Plan
        run: terraform plan -out=tfplan

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: prod-plan
          path: service-a/infra/prod/tfplan

  approval:
    name: 🔒 Manual Approval for PROD
    runs-on: ubuntu-latest
    needs: terraform-prod
    environment:
      name: production
      url: https://console.aws.amazon.com/
    steps:
      - name: Confirm
        run: echo "Manual approval waiting"

  apply:
    name: ☁️ Apply PROD Infra
    runs-on: ubuntu-latest
    needs: approval
    defaults:
      run:
        working-directory: service-a/infra/prod

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Init
        run: terraform init

      - name: Download Plan
        uses: actions/download-artifact@v4
        with:
          name: prod-plan
          path: service-a/infra/prod

      - name: Apply Terraform
        run: terraform apply -auto-approve tfplan
