name: Terraform - DEV Infrastructure (with Security)

on:
  push:
    branches: [main]
    paths:
      - 'service-a/infra/dev/**'
  workflow_dispatch:

env:
  AWS_REGION: us-east-1

jobs:
  terraform-security:
    name: Terraform CI & Security - DEV
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: service-a/infra/dev

    steps:
      - name: 📦 Checkout code
        uses: actions/checkout@v4

      - name: ⚙️ Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: ✅ Check Terraform Format
        run: terraform fmt -check -recursive

      - name: 🔍 Install tflint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          tflint --version

      - name: 🔎 Run tflint
        run: tflint --recursive

      - name: 🔐 Install tfsec
        run: |
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
          tfsec -v

      - name: 🚨 Run tfsec Scan
        run: tfsec .

      - name: 🛡️ Install checkov (optional, heavy)
        run: |
          pip install checkov
          checkov --version

      - name: 🚨 Run Checkov Scan (optional)
        run: checkov -d . || true

      - name: 🧪 Terraform Init
        run: terraform init

      - name: ✅ Terraform Validate
        run: terraform validate

      - name: 📉 Terraform Plan
        run: terraform plan -out=tfplan

      - name: 📦 Save Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dev-plan
          path: service-a/infra/dev/tfplan

      - name: 🚀 Apply Terraform
        run: terraform apply -auto-approve tfplan
